# Generated by Django 5.1.3 on 2024-11-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_category_options_alter_article_main_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
