# Generated by Django 5.1.3 on 2024-12-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_alter_comment_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_moderated",
            field=models.BooleanField(default=False),
        ),
    ]
